import os
import subprocess
import json
import datetime
from typing import Dict, Any

from tools.registry import registry, tool_error

def get_fit_date(shop_info_path: str) -> str:
    """Finds the latest valid YYYYMMDD directory containing a 'success' file."""
    if not os.path.exists(shop_info_path):
        return ""
    
    valid_dirs = []
    try:
        for item in os.listdir(shop_info_path):
            if len(item) == 8 and item.isdigit():
                # Validate date
                try:
                    datetime.date(int(item[0:4]), int(item[4:6]), int(item[6:8]))
                    valid_dirs.append(int(item))
                except ValueError:
                    pass
    except Exception:
        pass
        
    valid_dirs.sort(reverse=True)
    for date_int in valid_dirs:
        date_str = str(date_int)
        success_file = os.path.join(shop_info_path, date_str, "success")
        if os.path.exists(success_file):
            return os.path.join(shop_info_path, date_str)
            
    return ""

def augment_shop_knowledge(sample_path: str, mock: bool = False) -> str:
    """
    Finds the latest offline shop dictionary and appends related shops to the input file.
    
    Args:
        sample_path: Path to the input dataset file
        mock: If True, bypasses actual dictionary lookup
    """
    if not os.path.exists(sample_path):
        return tool_error(f"Sample path does not exist: {sample_path}")
        
    sample_path_new = f"{sample_path}_new"
    
    if mock:
        # Just copy the file and append a mock shop_info column
        with open(sample_path, 'r') as f_in, open(sample_path_new, 'w') as f_out:
            for line in f_in:
                items = line.strip().split("\t")
                if len(items) >= 15:
                    items.append("MockShop~.~1~.~MockTag~.~MockItem")
                    f_out.write("\t".join(items) + "\n")
                else:
                    f_out.write(line)
        return json.dumps({
            "status": "success",
            "message": f"MOCKED Shop augmentation complete. Saved to {sample_path_new}",
            "sample_path_new": sample_path_new
        }, ensure_ascii=False)
        
    # Real logic: find shop_info_dir and call add_shop_info.py
    shop_info_base_path = "/nfs/dataset-ofs-ssl/jiangyaogang/online/grocery_shop_info/data"
    shop_info_dir = get_fit_date(shop_info_base_path)
    
    if not shop_info_dir:
        # Fallback or error
        return tool_error("Could not find a valid shop_info_dir with 'success' flag.")
        
    # Call the original script assuming it is located at the internal legacy_scripts directory
    current_dir = os.path.dirname(os.path.abspath(__file__))
    legacy_script_dir = os.path.abspath(os.path.join(current_dir, "../apps/grocery_label/legacy_scripts"))
    script_path = os.path.join(legacy_script_dir, "add_shop_info.py")
    
    if not os.path.exists(script_path):
        return tool_error(f"Cannot find add_shop_info.py at {script_path}")
        
    try:
        subprocess.run(
            ["python", script_path, shop_info_dir, sample_path, sample_path_new],
            check=True, capture_output=True, text=True
        )
        return json.dumps({
            "status": "success",
            "message": f"Shop knowledge augmented successfully. Output: {sample_path_new}",
            "sample_path_new": sample_path_new
        }, ensure_ascii=False)
    except subprocess.CalledProcessError as e:
        return tool_error(f"add_shop_info.py failed with exit code {e.returncode}. Stderr: {e.stderr}")
    except Exception as e:
        return tool_error(f"Unexpected error: {str(e)}")

def check_requirements() -> bool:
    return True

SCHEMA = {
    "name": "augment_shop_knowledge",
    "description": "Appends offline auxiliary shop information to the dataset.",
    "parameters": {
        "type": "object",
        "properties": {
            "sample_path": {
                "type": "string",
                "description": "Absolute path to the input dataset file generated by the spark job"
            },
            "mock": {
                "type": "boolean",
                "description": "If true, mocks the augmentation process."
            }
        },
        "required": ["sample_path"]
    }
}

registry.register(
    name="augment_shop_knowledge",
    toolset="grocery",
    schema=SCHEMA,
    handler=lambda args, **kwargs: augment_shop_knowledge(
        sample_path=args["sample_path"],
        mock=args.get("mock", False)
    ),
    check_fn=check_requirements,
    emoji="🏪"
)
